### ISSUE TITLE
Cybernator - black screen freeze

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#101]
The game freezes to black screen during the first level, music keeps playing.
Same thing in "Assault Suits Valken" which is the Japanese version.
Translated version by "Aeon Genesis" freezes even faster.

**Comment by amoore2600** [comment]
I can confirm this happens too.

**Comment by paulb-nl** [comment]
Starting from release 0412 it freezes at the same place every time if you let the intro play. Release 0309 plays through the intro the first time but audio is gone the second time and then freezes at the end.

**Comment by James-F2** [comment]
Yes, Cybernator [U] freezes at the same place in the demo consistently, but Assault Suits Valken [J] does not freeze at the demo at all.

**Comment by James-F2** [comment]
Fixed.
Thank srg320!
