### ISSUE TITLE
Bugs Bunny Rabbit Rampage - Graphical Glitch ingame

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/SNES_MiSTer#106]
When you start a game, there is a line of "snow" on the left side of the middle of the screen which seems to be in front of any sprites/background and doesn't move when you scroll, this behavior doesn't appear on console

https://i.imgur.com/zHzO6yh.png

byuu has a note about this game that it:
"requires that HDMA during DMA stops the DMA"

Not sure if this is helpful here or not

**Comment by James-F2** [comment]
Fixed with latest PR.

**Comment by MP2E** [comment]
Can confirm! Closing this issue. I did find another problem with the game but I will make a seperate issue.

**Comment by MP2E** [comment]
Actually scratch my 2nd part of the last comment, just some user error on my part. This is fixed!
