### ISSUE TITLE
Marvelous: Another Treasure Island - Reset gets stuck at black screen

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/SNES_MiSTer#110]
As noted in #107 Marvelous gets stuck during reset at a black screen and will only recover if you re-load the ROM from the menu. Happens with fan translation v1.06 and v1.07, as well as the original japanese version. Marvelous is an SA-1 game

**Comment by James-F2** [comment]
Fixed with latest PR.

**Comment by MP2E** [comment]
can confirm!
