### ISSUE TITLE
Can´t save with lastest releases

### ISSUE THREAD

**Issue by Michinomiau** [MiSTer-devel/SNES_MiSTer#123]
Hi, i've just try to update las releases of Snes cores (.rbf) but if i try to save game i can´t. With 19/02/14.rbf core i use to save in game save menu and then with a save backup RAM option in the Mister menu, but with last releases that option doesn't exist. I'm doing something wrong? i'm must update something else than the .rbf file?

Thanks a lot

**Comment by sorgelig** [comment]
Update the MiSTer binary!
