### ISSUE TITLE
Colors are wrong for "T2 - The Arcade Game"

### ISSUE THREAD

**Issue by amoore2600** [MiSTer-devel/SNES_MiSTer#125]
The colors are wrong for "T2 - The Arcade Game"

The colors are: 

![IMG_20190821_203606](https://user-images.githubusercontent.com/3682337/63477798-ef253200-c454-11e9-92d8-f054947eba1a.jpg)

The colors should be:
![IMG_20190821_204143](https://user-images.githubusercontent.com/3682337/63477809-fa785d80-c454-11e9-9a1c-ee367a889544.jpg)

**Comment by MP2E** [comment]
Strange, I can't seem to reproduce this bug. It looks like the bottom image to me, I played for a few minutes. Does this occur later into the game?

**Comment by amoore2600** [comment]
**Additional information:**

ROM checksum:
/media/fat/SNES/6 Personal# md5sum T2\ -\ The\ Arcade\ Game\ \(USA\).SFC 
49a4cf748b491f6e7bdbfc86f2cf4d16  T2 - The Arcade Game (USA).SFC

Core version: SNES_20190719.rbf

Wrong colors happens from the beginning of the game.

**Comment by MP2E** [comment]
Still can't seem to reproduce on my end, I've tried like 5 different versions. Not really sure what could cause this kind of variance..

**Comment by amoore2600** [comment]
Want me to send you my ROM?

**Comment by MP2E** [comment]
I've got the same one according to md5sum

49a4cf748b491f6e7bdbfc86f2cf4d16  T2 - The Arcade Game (USA).sfc

I'll ask in the classic gaming discord and see if others see the same thing

**Comment by amoore2600** [comment]
Its taken me a while to figure out how to reproduce this bug but its definitely still here. I was wrong in thinking it was an HDMI cable issue that was originally causing it. 

The bug can be reproduced by:

1. Setting "SNAC" on the OSD for Serial  
2. Save settings
3. Reboot or Reset
4 Start the game using the SNAC controller 

Here is a video of the bug: https://youtu.be/bBgXDWc5sAY

**Comment by paulb-nl** [comment]
On your video you started the game with a Super Scope and I could reproduce that.  It does not happen with a normal SNES controller with SNAC.

Guess what happens when you start the game with the Scope on a real SNES.

![IMAG1018s](https://user-images.githubusercontent.com/2227984/74091340-930fa200-4ab6-11ea-95fc-1a8c5965c626.jpg)

**Comment by amoore2600** [comment]
WOW!!!! I totally did not expect that. Closing!!!
