### ISSUE TITLE
SFC player support

### ISSUE THREAD

**Issue by vinz2k** [MiSTer-devel/SNES_MiSTer#136]
Hello,

I think the NES core has support for NSF Player (but i’ve never test). Should it be possible to have a SFC Player for the SNES core ? (Maybe inspired with the SFC Player from Analogue SuperNT).

Thanks for all your work,

Snes core for MiSTer is for me a candy everyday 🥰.

Regards

**Comment by srg320** [comment]
It’s possible and I thought about it. 
But this will not happen until the core compiles stably. We are working to resolve this issue.

**Comment by sorgelig** [comment]
Linux on MiSTer already supports VGM/VGZ playback. 
You can download favorite tunes and play it on MiSTer in Linux using Midnight Commander.

**Comment by vinz2k** [comment]
Thanks for the info :) 

I’ll try it

**Comment by vinz2k** [comment]
Hello,

Any news regarding this topic ?

Or should we close the issue ?

Regards

**Comment by Beatatester** [comment]
If MiSTer does get an SPC player, it would be nice if it could play SPC2 files, since those are finally starting to catch on. The format seems to be [better suited for FPGA and real hardware](http://blog.kevtris.org/blogfiles/spc2_file_specification_v1.txt) than SPC in some ways.

**Comment by Chocobobobo** [comment]
Your wish has been granted, even if there is no interface, and some weird scratch when you load a new track, and doesn't use sp2 files.

**Comment by vinz2k** [comment]
Oh really ?

So we can load SPC file directly from the SNES core and they will play ?
Is that right ?

**Comment by vinz2k** [comment]
- Simple option to play SPC files. Audio only, without interface (srg320)

**Comment by James-F2** [comment]
Can this be closed now?

**Comment by vinz2k** [comment]
Sure
