### ISSUE TITLE
Megaman X2 graphical glitch

### ISSUE THREAD

**Issue by dukesilverfan** [MiSTer-devel/SNES_MiSTer#14]
There is a small graphical glitch with release 20181213, where the number '2' is missing from the intro screen when loading Megaman X2. I have not tested the rest of the game to see if there are other glitches, but I confirmed that Megaman X3 shows the 3 on the intro screen, and they are both Cx4 games.

This is by no means game-breaking, but this glitch may affect other games in different ways. 
![48361899_371767823576307_3391390774892429312_n](https://user-images.githubusercontent.com/20389961/50045897-951fd180-0068-11e9-9720-95e071475e20.jpg)
![48314212_521774631659727_6096470532075552768_n](https://user-images.githubusercontent.com/20389961/50045898-95b86800-0068-11e9-85e1-5d124f4a45c8.jpg)

**Comment by sorgelig** [comment]
this will be fixed along with with boxes.

**Comment by dukesilverfan** [comment]
Confirmed fix with Release 20181219.
