### ISSUE TITLE
Bad Apple Demo, will start with no audio randomly.

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#146]
https://www51.zippyshare.com/v/ttnvGs7Z/file.html (freeware).
Sometimes the audio will not play at random when loading the rom.
Tested with official 20190927 build.

EDIT: more info.
http://forums.nesdev.com/viewtopic.php?t=14856
It uses Indirect HDMA for audio decompression, in 32kHz.

Source code and rom file for this demo is available in the official page:
https://www.smwcentral.net/?p=viewthread&t=85373&page=1

**Comment by srg320** [comment]
Without this commit 0aafeb3568eb13281bca628a10946b2c6fc46c9b demo has a sound always, otherwise Magical Drop freezes in Endless Mode. I think the game is more important than the demo. Nevertheless, I am interested to know how the demo works on real console.

**Comment by James-F2** [comment]
I think a lot more people are familiar with the Bad Apple demo than Magical Drop.
I have 5 SNES consoles, I will test the Bad Apple demo and report back.

**Comment by James-F2** [comment]
On real hardware the demo audio boots consistently, BUT, audio sometimes stops in the middle of the demo while video continues running.
Also, I can see a flickering scanline on the bottom left corner with the hardware which does not appear in the core or bsnes.

**Comment by srg320** [comment]
In the core the sound also sometimes stopped somewhere in the middle of the video, so we slightly adjusted DSP frequency because of this demo (but this is not entirely correct). Audio stopping happens in the different spots because the frequency of both quartz resonators (21MHz and 24MHz) is slightly different on each console.

**Comment by MP2E** [comment]
This appears to be fixed as of #148

**Comment by James-F2** [comment]
Fixed.
