### ISSUE TITLE
Super Mario World - Super Mario Bros. 4 (Japan) - Sound Issue

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/SNES_MiSTer#150]
Hi,
When Mario take this type of coin (https://www.pinterest.jp/pin/493847915387587483/). 
The sound seems too low.
I used this version of the core "Release 20190927"
Thanks for the check.
Wwark

**Comment by MP2E** [comment]
Seems correct to me

MiSTer:
https://cdn.discordapp.com/attachments/497145588446396416/630946688743243787/coin_mister.flac

Real SNES:
https://youtu.be/TdTm6BfMGko?t=89

**Comment by James-F2** [comment]
Sounds correct.
Can be closed.

**Comment by wwark** [comment]
Thank you for the check I will check next time with youtube video from real hardware.
