### ISSUE TITLE
Wolf3d + mouse

### ISSUE THREAD

**Issue by gyurco** [MiSTer-devel/SNES_MiSTer#158]
Wolfenstein 3D uses auto controller polling, which asserts the joystick latch in every 16th clock. But this resets the mouse before the movement info is fetched. I wonder if the CPU detects the 16th bit and decides to not assert the latch if it's zero, or how the mouse supposed to work in this game.

**Comment by gyurco** [comment]
Some sources says the latch is only issued once/frame, not in every 16th clock.

**Comment by sorgelig** [comment]
fixed
