### ISSUE TITLE
Tales of Phantasia glitchy menu graphics

### ISSUE THREAD

**Issue by softtest03** [MiSTer-devel/SNES_MiSTer#159]
Load the save file. Open up the game's menu (SNES button X). Click on "items" ("アイテム"). The graphics behind the item list's text will glitch as you move around with the D-Pad.

Save file: https://ufile.io/z8cnnyu5

I'm playing with an unmodified Japanese rom.

**Comment by srg320** [comment]
On bsnes, snes9x and no$sns I see the same thing. Сan you show how it looks on real SNES?

**Comment by MP2E** [comment]
It does the exact same thing on my 1chip SNES, I don't think this is a MiSTer bug

**Comment by softtest03** [comment]
Sorry, I don't have an SNES to confirm this but I will assume that you are right and it's a false positive.

**Comment by MP2E** [comment]
No problem! I think it's always good to have someone double check if behavior seems weird.
