### ISSUE TITLE
Shin Nihon Pro Wrestling Kounin - '95 Tokyo Dome Battle 7 (Japan) 

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#163]
https://github.com/byuu/bsnes/issues/214

**Comment by James-F2** [comment]
Fixed bsnes,, is was IRQ related.

**Comment by James-F2** [comment]
Fixed!

**Comment by Max833** [comment]
Here is this fixed issue now: https://archive.is/o/Ghl0y/https://github.com/byuu/bsnes/issues/214
