### ISSUE TITLE
[Suggestion] Open the OSD menu when core loads like the NES core

### ISSUE THREAD

**Issue by klaritan** [MiSTer-devel/SNES_MiSTer#167]
The NES core seems to open the OSD menu when you load a core now. This is a great change.

Could we enable this for SNES? I think the Genesis core is missing it, but I'm not sure if I should create another issue on that repo for it.

**Comment by James-F2** [comment]
Implemented. :smiley: 
Can be closed.

**Comment by klaritan** [comment]
Thanks!
