### ISSUE TITLE
Contra 3- Stage 3 bug

### ISSUE THREAD

**Issue by black-francis** [MiSTer-devel/SNES_MiSTer#171]
Using SNES_20191117.rbf with a no-intro rom, American region.

On Stage 3 you can see a blue line on the left hand side of the play area that shouldn't be there.

![IMG_5101](https://user-images.githubusercontent.com/44230562/71322963-9e3a4e80-24c5-11ea-85c1-5b9e8cacf2f4.JPG)

**Comment by Max833** [comment]
Real hardware issue. https://github.com/byuu/bsnes/issues/248
