### ISSUE TITLE
15 Khz?

### ISSUE THREAD

**Issue by manast** [MiSTer-devel/SNES_MiSTer#173]
Hello!,

I am trying the Mist port of the core and it does not seem to support 15Khz, however issues are disabled in the Mist repo, so I just wonder if Mister version supports it and it is just not ported, or maybe not supported at all?

**Comment by sorgelig** [comment]
15KHz is supported on MiSTer.

**Comment by manast** [comment]
ok, so in theory it should also work in MiST, I will see if I can make it work then.
