### ISSUE TITLE
Super Mario World Cape Powerup Sound Too Slow

### ISSUE THREAD

**Issue by daroga** [MiSTer-devel/SNES_MiSTer#174]
Hello!

This is my first time posting an issue. Forgive me if I mess things up.

I just played through all of Super Mario World. I noticed the sound effect that plays when you get the feather power up plays at about half speed (compare to the sound effect here on real hardware at about 10:53: https://youtu.be/0CcgWb4GhEA?t=650). I didn't notice any other issues, sound or otherwise, throughout the game.

Thanks!

**Comment by James-F2** [comment]
Here mister sounds exactly like on the real console and this video.

**Comment by James-F2** [comment]
@sorgelig 
If OP does not reply shortly, this can be closed.

**Comment by daroga** [comment]
I'll chalk it up to an odd issue on my end. If no one else is having a problem, let's call it closed.

Thanks, everyone, for all of your work!
