### ISSUE TITLE
Goodbye Anthrox demo, wrong colors

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#186]
http://www.pouet.net/prod.php?which=7515

Small video from sd2snes (3.5MB):
[goodbye video.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/4045380/goodbye.video.zip)

No transition before demo on Mister, because there is nothing in PPU.
On sd2snes you can see shifting letters from sd2snes menu.

Mister core 20200105, wrong color:
![20200110_124011](https://user-images.githubusercontent.com/31185814/72147067-73496900-33a6-11ea-8b09-e952a15ad0b3.jpg)

**Comment by James-F2** [comment]
Another demo by anthrox called "Anthrox - Legendary Intro Collection" has the logo colors scrambled.
http://www.pouet.net/prod.php?which=12926

Mister snes 20200105:
![20200110_140738](https://user-images.githubusercontent.com/31185814/72152087-9f6ae700-33b2-11ea-9422-f71b39dfeec6.jpg)

**Comment by paulb-nl** [comment]
This is fixed with latest commits

**Comment by James-F2** [comment]
yep
