### ISSUE TITLE
Secret of Mana (Germany)

### ISSUE THREAD

**Issue by graschbaten** [MiSTer-devel/SNES_MiSTer#192]
There are many graphic issues in the background and this game isnt playable.
The USA Version havnt got this issue.
Core: SNES_20200108.rbf
I test with older Cores but same result

**Comment by paulb-nl** [comment]
I have tried this for a short while but it worked fine on the same core. What is the size and CRC of your ROM?

**Comment by graschbaten** [comment]
Thx for your reply.

Database match: Secret of Mana (Germany)
Database: No-Intro: Super Nintendo Entertainment System (v. 20180813-062835)
File/ROM SHA-1: AB8A31BFB4CF0CE19B96893A31442FFBFD8D0BEB
File/ROM CRC32: B069BB3A

Now i thing i got this Rom running too but this is only thinking ;)
