### ISSUE TITLE
Wild Guns - Constant Flicker and Slowdown.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/SNES_MiSTer#196]
This issue was spotted on TheHandleBarGamer's recent stream, but because of his capture setup you don't see the actual flickering.  The game also runs well below normal speed.  

https://www.youtube.com/watch?v=ZkKCiWrW9to&feature=youtu.be&t=2116

I personally tested and confirmed using 20200108 release.

**Comment by paulb-nl** [comment]
Use the 20191117 release for now. 20200106 and 0108 have issues.

**Comment by Peredonov** [comment]
> Use the 20191117 release for now. 20200106 and 0108 have issues.

What is the best way to revert to an earlier release? I tried manually replacing 20200108 with 20191117 and the core would not load, neither would it after manually replacing 0108 back. Using the update script was the only way to be able to load the core again.

**Comment by James-F2** [comment]
Latest commit fixed this.
https://github.com/MiSTer-devel/SNES_MiSTer/commit/f62491cedd5b563084e2d63b0898c9b162324f4c

**Comment by paulb-nl** [comment]
> What is the best way to revert to an earlier release?

Just copy the rbf to the folder. I use WinSCP with SFTP.

**Comment by SegaSnatcher** [comment]
I tried a test build with latest commits and it did indeed fix this issue.  Thanks
