### ISSUE TITLE
Masters New - Harukanaru Augusta 3 (scrambled graphics)

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#198]
Same thing in Pebble Beach no Hatou New.
Not sure if SA-1 related or when it started to happen.

![20200121_224232-Masters New - Harukanaru Augusta 3 (Japan)](https://user-images.githubusercontent.com/31185814/72841708-9675f180-3c9f-11ea-8d61-ee07fa8ca323.png)

**Comment by paulb-nl** [comment]
It seems to be caused by this commit 044c4870295f2ae3fb9aa3a8c72b847cccc0fd67

**Comment by sorgelig** [comment]
ok, i've reverted it
