### ISSUE TITLE
Homebrew "Commodore 64 Collection" crashes

### ISSUE THREAD

**Issue by sajattack** [MiSTer-devel/SNES_MiSTer#203]
First off, let me be clear, this is a SNES rom, which is a collection of Commodore 64 games. Upon pressing start at the main menu, it goes to a screen full of the "@" symbol. I checked the same ROM in bsnes, and it is supposed to take you to a secondary menu to pick a game. 

The hashes of this rom are as follows: 
```
md5: 19b3b9a9282a6a65abef62cff025c078
sha1: 1bc3cfffa56db6fb2040fd721e210d028ddfbad7
sha256: ca12735865b0e4bfa7fb2edddecb74ca9d4e269718f9bc1e5acd20ff829aa782
crc32: 1888ea3f
```

**Comment by sorgelig** [comment]
Does it has any additional custom chips in cart?

**Comment by sajattack** [comment]
How do I check?

**Comment by sorgelig** [comment]
fixed in today's release.
