### ISSUE TITLE
WILD GUNS: Unplayable after starting game, heavy flickering and slowdown

### ISSUE THREAD

**Issue by cpmattes** [MiSTer-devel/SNES_MiSTer#207]
Like mentioned in title, after starting US or JAP Version of Wild Guns with SNES_20200108.rbf everything seems to be fine, title screen and menu are flawless, controller is reacting. After choosing a character and starting the game, the picture is flickering heavily and gameplay is evenly slowed down. Using 128MB ram expansion, setup cooled passive and with a noctua.

**Comment by paulb-nl** [comment]
This has already been fixed.

@sorgelig please make a new release

**Comment by sorgelig** [comment]
i didn't release yet because i see debates when one commit fixes one thing but breaks others. So i'm unsure if it's ready to release or not.

**Comment by paulb-nl** [comment]
It is ready for release. The regressions have been fixed.

**Comment by sorgelig** [comment]
alright. will release tomorrow

**Comment by Left-Empty** [comment]
Hello,
I have just tried it, and the issue seems to still be here.

**Comment by paulb-nl** [comment]
Works fine here:
https://youtu.be/UZvSomwdStI

**Comment by cpmattes** [comment]
Last update fixed it for me!

**Comment by Left-Empty** [comment]
It seems my wonderful little MiSTer wants me to look bad here: for two days the game exhibited the glitch. 
I try again today after watching paulb-nl's video, using the US version: it works. I tried again my Japanese version. It works.
I apologize.

**Comment by SegaSnatcher** [comment]
> Last update fixed it for me!

Probably best to close this issue now.  Thanks
