### ISSUE TITLE
Equinox graphic glitch

### ISSUE THREAD

**Issue by Aquas77** [MiSTer-devel/SNES_MiSTer#213]
Character sprite is clipping into some layers. Only noticed it in this particular room, but fairly positive it is abnormal behavior.

Video: https://www.twitch.tv/videos/578946319

**Comment by paulb-nl** [comment]
Any way to get there quickly?

**Comment by Aquas77** [comment]
Not that I can find out unfortunately. It's the 4th dungeon and getting to that room is kinda annoying too. The cheats I found none let you skip the dungeons, but there are infinite life and keys cheats, if you felt like breezing through it. I'm doing a full playthrough so I'll report any other issues I find.

**Comment by paulb-nl** [comment]
With a save file and some key cheats I could get there easily and I have verified that it happens on a real SNES.

https://youtu.be/RNTP8tl1yYY

**Comment by Aquas77** [comment]
Oh, my apologies. I had someone check some real hardware footage and they said it wasn't occurring. I'll try to double verify next time I report. Thanks for checking it out.
