### ISSUE TITLE
Emudetect test rom shows Dog when booting after loading a game.  

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/SNES_MiSTer#215]
I'm using SNES 1 ram setting and if I load this test after loading a game it shows the Dog, but if I go straight to the test from a cold boot it shows "Original Hardware" picture. Edit: Additional info, if I load the test rom a 2nd time after the initial Dog result I get "Original Hardware".  Curious 

Is this a problem with the test rom or the core?

**Comment by paulb-nl** [comment]
It is because the core starts with palette memory all zeroes and then it shows the dog. The second time  the palette is filled with whatever the previous rom put there.

**Comment by James-F2** [comment]
I thought the memory pattern is reset each time a new rom is loaded. ?

**Comment by SegaSnatcher** [comment]
I'm just curious if this also happens on a real SNES or is it just a MiSTer issue?

**Comment by paulb-nl** [comment]
> I thought the memory pattern is reset each time a new rom is loaded. ?

Yes but not all memory currently. like the palette ram.

> I'm just curious if this also happens on a real SNES or is it just a MiSTer issue?

It depends what is in the palette ram on cold boot. A real SNES probably does not have all zeros in palette ram on boot

**Comment by SegaSnatcher** [comment]
So technically since this isn't acting like a real SNES would should I keep this issue open or no?

**Comment by sorgelig** [comment]
fixed by filling a "random" data.
