### ISSUE TITLE
Super Mario RPG save was reset all progress lost

### ISSUE THREAD

**Issue by will7046** [MiSTer-devel/SNES_MiSTer#224]
Using current version, auto save is enabled. My previous Super Mario RPG save file loaded just as normal at startup of the game, I then reloaded the game and all of my progress was lost. I created a new save, it would save and let me reload 3 times in a row, the 4th time it reset all of my progress again. I had used this save since SA1 was implemented with no issues. I had not updated my Mister in about a month, not sure which version I was on previously.

**Comment by aberusugi** [comment]
32mb, 64mb, 128mb SDRAM?

Asking because I just recently completed a full playthrough of the game successfully and am using 128mb SDRAM module from misterfpga.co.uk for reference and it passes testing at 140mhz.

**Comment by will7046** [comment]
32MB Ram module, thanks

**Comment by will7046** [comment]
Tried again today with latest Main mister release, would save and then reload game after about 10 times of doing this in a row it would reset my progress again eventually.

**Comment by aberusugi** [comment]
Looks like you got a ball rolling. 

https://github.com/MiSTer-devel/SNES_MiSTer/pull/225

**Comment by James-F2** [comment]
Fixed in Release 20200929.
Can be closed.
