### ISSUE TITLE
Selecting Save Backup RAM from menu does not show a notification

### ISSUE THREAD

**Issue by osaeed18** [MiSTer-devel/SNES_MiSTer#227]
Hi all, when I select a game, complete a level and the game prompts me to save, I choose the Save Backup RAM option and I do not see a notification on the bottom, top or anywhere on the screen that I chosen the option. 

Can this be added as a feature in a future release? 

Thank you

**Comment by sorgelig** [comment]
On I/O board you may see disk LED activity on save.

**Comment by osaeed18** [comment]
Hi sorgelig, I think it would be pretty neat to have some save notification.  In the program Retroarch, you can see something as a reference to what can be added as a notification feature to the SNES MiSter core. 

![20200713_115604](https://user-images.githubusercontent.com/35477975/87326779-33a03d00-c501-11ea-8731-5b6aa33b04ec.jpg)

Just my thoughts. Thank you for your contribution to this core.
