### ISSUE TITLE
Slowdown when selecting "Game Start" at Title Screen for Rockman X2

### ISSUE THREAD

**Issue by JDash247** [MiSTer-devel/SNES_MiSTer#229]
Tested on SD2SNES and real cart.

When starting Rockman X2 and getting to the title screen, I get slowdown when selecting and confirming "Game Start" in the menu.

**Comment by paulb-nl** [comment]
This is caused by commit eab51bb9635ae440b9b8af56810ddce56ade42d7 slowing down the CX4 clock. Reverting the commit fixes the slowdown.

**Comment by sorgelig** [comment]
reverting that commit will make Rockman die in attraction mode.

**Comment by paulb-nl** [comment]
Yeah but changing it to 18Mhz is not a good fix. As you can see it is too slow now.

**Comment by JDash247** [comment]
Slowdown and attraction mode fixed in 200929
