### ISSUE TITLE
Flickering title screen

### ISSUE THREAD

**Issue by DasBoot2000** [MiSTer-devel/SNES_MiSTer#234]
The words STRIKE GUNNER at the top of the title screen are flickering on MiSTer but not on real hardware

**Comment by paulb-nl** [comment]
It does flicker on real hardware too

**Comment by sorgelig** [comment]
probably it's a game tuned for specific SNES HW revision.

**Comment by sorgelig** [comment]
As paulb-nl confirmed with real HW i guess it can be closed

**Comment by DasBoot2000** [comment]
Ok, thx guys - I close
