### ISSUE TITLE
Odd flashing on part of screen while playing super mario all stars + super mario world

### ISSUE THREAD

**Issue by sethenstien** [MiSTer-devel/SNES_MiSTer#237]
At random times in Super Mario All Stars + Super Mario World a line of pixels flash colors on the right side of the screen. This is the best picture I have for now. Thanks.
![20200916_180738](https://user-images.githubusercontent.com/56380280/95008945-9b879080-05e3-11eb-92d0-df4b364a9368.jpg)

**Comment by Kitrinx** [comment]
Please show the equivalent on real hardware, to verify this is not simply game behavior.

**Comment by paulb-nl** [comment]
This happens on Mario World when CPU Turbo is enabled.

**Comment by James-F2** [comment]
Yep, caused by Turbo.
Issue can be closed, user error.

![20201009_100930](https://user-images.githubusercontent.com/31185814/95553918-01c34780-0a18-11eb-8364-0c9044e688e6.jpg)
