### ISSUE TITLE
Issue loading some .bs files, like Marvelous - Camp Arnold Course - Dai-1-shuu (Japan) (SoundLink).bs

### ISSUE THREAD

**Issue by Chocobobobo** [MiSTer-devel/SNES_MiSTer#242]
The title says it all. Here is what we have currently (using the patched US Bios)

![20201017_222430-Marvelous - Camp Arnold Course - Dai-1-shuu (Japan) (SoundLink)](https://user-images.githubusercontent.com/23947970/96352939-efa47180-10c7-11eb-9567-bafad14a5527.png)

Please note that the exact same .bs file works fine on SD2SNES.

Thanks for looking into it!

**Comment by srg320** [comment]
Some BS roms contain incorrect values in the header. 
This will be fixed in Main in next release.

**Comment by Chocobobobo** [comment]
Just saw your commit, thanks a lot for the quick turnaround.
I will do more testing once I could check your fix.

**Comment by Chocobobobo** [comment]
Fix confirmed, thank you.

![20201018_142752-Marvelous - Camp Arnold Course - Dai-1-shuu (Japan) (SoundLink)](https://user-images.githubusercontent.com/23947970/96367512-96335580-114e-11eb-8f79-56dc248bc174.png)
![20201018_142837-Marvelous - Camp Arnold Course - Dai-1-shuu (Japan) (SoundLink)](https://user-images.githubusercontent.com/23947970/96367515-99c6dc80-114e-11eb-9c97-2e03612c2fd4.png)
