### ISSUE TITLE
BS-X: "Kirby no Omochabako - Baseball" and "Kirby no Omochabako - Pinball" don't boot

### ISSUE THREAD

**Issue by TLPD-AVW** [MiSTer-devel/SNES_MiSTer#243]
Two games from Kirby' Toy Box series - "Kirby no Omochabako - Baseball" and "Kirby no Omochabako - Pinball" refuse to load through BS-X English DRM-free BIOS. Trying to load either of them produces Error 09.
![20201017_201457-Kirby no Omochabako - Baseball (Japan)](https://user-images.githubusercontent.com/70150033/96353192-8f66fd00-10d2-11eb-992b-26b42f6387be.png)
![20201017_202943-Kirby no Omochabako - Pinball (Japan)](https://user-images.githubusercontent.com/70150033/96353321-7743ad80-10d3-11eb-97c2-76ebed1c0f49.png)
Five other games from that series do not suffer from this issue and load properly. These two .bs roms run properly with the same BIOS on Snes9x.

**Comment by srg320** [comment]
Some BS roms contain incorrect values in the header. 
This will be fixed in Main in next release.

**Comment by Chocobobobo** [comment]
Both are fixed after your earlier commit, thanks srg320.

![20201018_143249-Kirby no Omochabako - Baseball (Japan)](https://user-images.githubusercontent.com/23947970/96367572-03df8180-114f-11eb-9ed8-c0edd6a0c0f1.png)
![20201018_143313-Kirby no Omochabako - Baseball (Japan)](https://user-images.githubusercontent.com/23947970/96367574-0510ae80-114f-11eb-92c6-0c0e1589c772.png)

**Comment by srg320** [comment]
Both games boot fine for me, tested several times.

**Comment by Chocobobobo** [comment]
Pinball is fine now, just checked with your snes: fix has_bsx_slot init value commit.

**Comment by TLPD-AVW** [comment]
Both games start properly with the latest releases of Main and SNES core. I'm closing the issue, thanks a lot for your work!
