### ISSUE TITLE
Two more .bs files not being recognized, even after this fix (* snes: fix patch of incorrect BS header values)

### ISSUE THREAD

**Issue by Chocobobobo** [MiSTer-devel/SNES_MiSTer#244]
First of all, please note that those tests have been done using an updated MiSTer and SNES including your commit (* snes: fix patch of incorrect BS header values)

I found two more .bs files not booting using the default japanese BIOS, but are working fine on bsnes for example.

Those two games are:
Spriggan Powered BS - Dai-3-wa (Japan) (SoundLink)
Spriggan Powered BS - Prelude (Japan) (SoundLink)

Thanks for looking into it.
Right now, this is what we have:

![spriggan](https://user-images.githubusercontent.com/23947970/96446208-6436f780-1211-11eb-8048-27324b253747.png)

**Comment by Chocobobobo** [comment]
Extra info

Spriggan Powered BS - Prelude (Japan) (SoundLink) loads with the hacked US BIOS, but nothing with the original BIOS.

So there is still something going, based on the BIOS that you are using. (https://github.com/MiSTer-devel/SNES_MiSTer/issues/241)

**Comment by srg320** [comment]
Both games load fine with japanese bios.
![20201025_115231-Spriggan Powered BS - Prelude (Japan) (SoundLink)](https://user-images.githubusercontent.com/40274294/97106466-79f16480-16ca-11eb-91c1-7348930cca0e.png)
![20201025_115306-Spriggan Powered BS - Dai-3-wa (Japan) (SoundLink)](https://user-images.githubusercontent.com/40274294/97106467-7a89fb00-16ca-11eb-96dc-66ee7d3dfb5e.png)

**Comment by Chocobobobo** [comment]
Not sure how this is related, but I rechecked after your earlier commit snes: fix has_bsx_slot init value, and it is fine now, thanks srg320 !
