### ISSUE TITLE
Ogre Battle - The March of the Black Queen - Sprite issues

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/SNES_MiSTer#249]
It is in the beginning of the game after start a new game (visible on USA version and Japanese version)

![20201101_172022-Ogre Battle - The March of the Black Queen (USA)](https://user-images.githubusercontent.com/469461/97808431-15547d80-1c67-11eb-8158-b97ac40eb5ba.png)
![20201101_172106-Densetsu no Ogre Battle - The March of the Black Queen (Japan) (NP)](https://user-images.githubusercontent.com/469461/97808432-15ed1400-1c67-11eb-8e9a-00f8e8a3ff36.png)
 
Thanks,

**Comment by paulb-nl** [comment]
There are 2 Japanese versions.
Normal: Size: 1536 KB, CRC32: 65CD17E3
Nintendo Power: Size 2048 KB, CRC32 3E50C7C2. This one has an extra "Load" option between New game and continue.

I can only get the green tiles to appear by loading the Japanese Nintendo Power version. After that the English version will also have the green tiles.

Reloading the core does not fix it. Only rebooting to the menu and then reloading the core works.

**Comment by wwark** [comment]
Thank you @paulb-nl.
I confirm the issue happens if we launched Japanese Nintendo Power Version first.

**Comment by wwark** [comment]
Fixed by this commit (https://github.com/MiSTer-devel/SNES_MiSTer/commit/57c00ce575e845be7b7ca56c11e7550240a0df49)
Thanks @srg320 !

**Comment by wwark** [comment]
For information (maybe related to my build), I have some issue to launch BS games.
After select the gender, the core becomes very slow (hang).
I don't have this behaviour with the last release RBF.

**Comment by wwark** [comment]
Oups I forgot to reopen this issue.
Do you think it is link to my compilation or is it a regression ?
Thanks,

**Comment by wwark** [comment]
Last update Sattelaview working.
Thanks !
