### ISSUE TITLE
Starfox GSU explosion dithered polygons bug

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#25]
There is a bug with visible dithered blue triangle polygons flying from an explosion when shooting an orange asteroid (second level), that is not present on the real cart, see image.
RedGuy's GSU on the SD2SNES also had this bug in beta, but it was fixed it.

Bug left,, real cart right.
https://cdn.discordapp.com/attachments/430550791552630800/442430284844105736/Starfoxbug4.png

RedGuy's fix:
https://github.com/mrehkopf/sd2snes/commit/ff85304602da62222afbe0575178b4467833b109

RedGuy on discord:
> The post-dithered color was used to test for transparency in plot.  It should use the pre-dithered color.

**Comment by sorgelig** [comment]
did you try pseudo-transparency: blend mode?

**Comment by James-F2** [comment]
fixed
