### ISSUE TITLE
Super Mario World (USA) - Graphical glitch

### ISSUE THREAD

**Issue by bibou42** [MiSTer-devel/SNES_MiSTer#253]
Hi!
While fighting the boss in Ludwig's Castle, I noticed some graphical glitches (see picture).
I can't test on real hardware but the glitch doesn't happen in bsnes emulator.
I'm providing a save file to test.

![SMW_Glitch](https://user-images.githubusercontent.com/18500303/103412804-378b4e80-4b77-11eb-85a2-8131771cd9e3.JPG)

[Super Mario World (USA)_glitch.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/5757387/Super.Mario.World.USA._glitch.zip)

**Comment by Max833** [comment]
Maybe that is because of that
https://github.com/mrehkopf/sd2snes/issues/126

**Comment by James-F2** [comment]
That's normal on real console.

**Comment by sorgelig** [comment]
@James-F2 thanks for checking it!

**Comment by bibou42** [comment]
Thanks for checking :)

**Comment by paulb-nl** [comment]
@James-F2 Did you only try it with an SD2SNES?

I have used a real Super Mario World cart on a APU-01 console and there are no glitches at all while MiSTer shows a lot of glitches when Ludwig is rotating or standing at the right edge.

APU-01:
https://youtu.be/rdufK1PF8eg

MiSTer:
https://youtu.be/WxhqSj8h76E

**Comment by bibou42** [comment]
Fixed in Release 20210620
