### ISSUE TITLE
Graphical Glitches in Super Mario Bros 2 in Super Mario All Stars + Super Mario World

### ISSUE THREAD

**Issue by sethenstien** [MiSTer-devel/SNES_MiSTer#256]
Specifically in world 4-3 of Super Mario Bros 2 I get these garbled blocks. 
![vlcsnap-2021-02-03-23h11m27s524](https://user-images.githubusercontent.com/56380280/106847828-5351ab00-6675-11eb-8c6c-adda7f7e4f9d.png)

**Comment by paulb-nl** [comment]
This is a bug in the game. I have reproduced it on a SNES with original Super Mario All Stars cartridge and an Everdrive with Super Mario All Stars + World.

If you lose all your lives on 4-3 and choose continue on the game over screen and then go back to that place in 4-3 then the tiles are garbled.
