### ISSUE TITLE
Uniracers, 2P & VS  mode, second player bug

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#26]
When playing a 2 player game, the second player is hovering above the track even when not moving.

![20190126_180416](https://user-images.githubusercontent.com/31185814/51789791-6895c400-2195-11e9-9bd9-d0ace1874b7d.jpg)

**Comment by James-F2** [comment]
More info;
The bottom player (player 2) nose is always facing left even though he's driving to the right.
When both players on a single screen, the bottom player disappears from the bottom screen.

Something even stranger:
When the bottom player comes close to the top player from the left, he suddenly teleports to the right of the top player.
Moreover, there is a part of the upper screen where the bottom player can't be in where I ..
![20190225_091131](https://user-images.githubusercontent.com/31185814/53320828-8151e080-38df-11e9-94d7-0ee68d56c2b8.jpg)

It seems like a DMA problem with Object Attribute Memory.
As explained here:
https://youtu.be/K7gWmdgXPgk?t=12m47s

**Comment by srg320** [comment]
You are right and this problem is already being [discussed](https://forums.nesdev.com/viewtopic.php?f=12&t=18447)
This will be fixed in future releases.

**Comment by paulb-nl** [comment]
Could you test this build? https://github.com/paulb-nl/SNES_MiSTer/tree/oam/releases

I have made big changes to sprite evaluation to be closer to a real SNES so it needs testing to make sure there are no regressions.

**Comment by James-F2** [comment]
Will do, right now.

**Comment by James-F2** [comment]
I have tested 20+ game including Uniracers.
I see no glitches at all.

**Comment by paulb-nl** [comment]
Thanks for testing James. Good to hear there are no issues.

**Comment by James-F2** [comment]
@srg320 mentioned on the nesdev thread that he is reworking the PPU sprite handling too,, so maybe he has a fixed PPU version too?

**Comment by srg320** [comment]
Of course, but later, now I'm busy SA1.

**Comment by James-F2** [comment]
This bug has been fixed with paulb_nl request.
https://github.com/MiSTer-devel/SNES_MiSTer/pull/44

**Comment by sorgelig** [comment]
ok. then I close it.
