### ISSUE TITLE
216p Crop Offset half-broken

### ISSUE THREAD

**Issue by rikard-softgear** [MiSTer-devel/SNES_MiSTer#266]
Only 2, 4, -2 and -4 works as expected, anything higher or lower behaves as 4 or -4 respectively.

**Comment by SegaSnatcher** [comment]
I believe this is because for SNES anything over the 224 just shows black lines.   On NES you can use all crop offset values with hide overscan turned off because it will show graphic information beyond 224 lines, same with Genesis core with border enabled.

**Comment by sorgelig** [comment]
because 224-216 is 8 lines so only range -4..+4 is possible for such resolution
