### ISSUE TITLE
  S-RTC and SPC7110 + RTC4513 to make use of MiSTer RTC

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/SNES_MiSTer#267]
The S-RTC and SPC7110 + RTC4513 support doesn't seem to make use of MiSTer's RTC module. It would be nice if it did, so that the involved games use the real date and time without needing any adjustments.

Discussed in this thread:
https://misterfpga.org/viewtopic.php?f=8&t=1155

**Comment by bootsector** [comment]
I've tested latest core with Tengai Makyou Zero with a RTC board v1.3 and without any network connectivity. I was able to start the game, save and restore normally. Time was saved/restored correctly. What exactly is the issue here?

**Comment by ajgowans** [comment]
Confirmed working as designed
