### ISSUE TITLE
SPC Player has incorrect "initial register values"

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/SNES_MiSTer#268]
I believe the audio bugs I've observed in multiple SPC files when using the SPC player might be related to it not passing this test.

[initial_regs.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/6292702/initial_regs.zip)

From the readme for the test:

```
SNES SPC file loader tests
--------------------------
These verify basic operation of an SPC player on SNES hardware.

They report the result via a series of beeps:

	Beeps			Result
	- - - - - - - - - - - - - - - - - - - - - - - - -
	low				Passed
	low high		General failure
	low high low	Failure code 2
	low high high	Failure code 3
	etc.

Only the first failure is reported. Sub-tests are run in the order of their codes. Once a test is done, it re-runs the bootloader, so the SNES doesn't have to be reset before loading another SPC file.


initial_regs.spc
----------------
Verifies initial register values. Failure codes:

	2: CPU registers
	3: $F0-$FF registers
	4: DSP registers
```

The test goes low-high-high indicating failure code 3.

The behavior for multiple SPCs is not functioning currently, and it's all tied into the initial start of the song. Actraiser SPC's fail to go beyond the first split second of playback. Some Chrono Trigger songs have messed up audio for the first sample, etc...

[ActRaiser.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/6292705/ActRaiser.zip)

[Chrono Trigger.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/6292707/Chrono.Trigger.zip)

For example:

[ct-battle-1.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/6292728/ct-battle-1.zip)

**Comment by thehughhefner** [comment]
As of v211214 I get Failure code 3.

**Comment by birdybro** [comment]
Resolved with https://github.com/MiSTer-devel/SNES_MiSTer/pull/334
