### ISSUE TITLE
H-IRQ fires when set to $FFFF

### ISSUE THREAD

**Issue by paulb-nl** [MiSTer-devel/SNES_MiSTer#275]
In the Mode 7 test #274 H-IRQ starts at 0. After pressing L once the interrupt doesn't fire on a real SNES because $FFFF is written to $4207/8 but on MiSTer I have to press L twice before the interrupt stops firing.

**Comment by srg320** [comment]
Fixed.

**Comment by paulb-nl** [comment]
Thanks srg320!
