### ISSUE TITLE
Full Throttle - All-American Racing (USA)

### ISSUE THREAD

**Issue by paulb-nl** [MiSTer-devel/SNES_MiSTer#279]
The bottom line on the water bike race has garbage.

MiSTer:
![20210507_155126-Full Throttle Racing (U)x2](https://user-images.githubusercontent.com/2227984/117541850-27e4b080-b016-11eb-962c-3b8225a00fff.png)

SNES:
![full_throttle_racing_c](https://user-images.githubusercontent.com/2227984/117541871-3cc14400-b016-11eb-9d25-f5d1ca525da9.png)

There are multiple issues. First issue is that H-IRQ at line 143 is too early. The game writes $0104 (260) to `HTIME`  and then changes from V-IRQ to H-IRQ. Now `IRQ_N` goes low after the switch from V-IRQ to H-IRQ because of `HIRQ_VALID` = 1. The game uses WAI to wait until H 260 but `IRQ_N` is low so immediately exits WAI at H 226.

Here $11 is written to $4200 and `P65_IRQ_N` goes low too early:
![virq_to_hirq](https://user-images.githubusercontent.com/2227984/117542410-d7228700-b018-11eb-8fbe-630540e6ea6c.png)

WAI exits too early:
![wai_too_early](https://user-images.githubusercontent.com/2227984/117542507-32ed1000-b019-11eb-86aa-6d8efa943263.png)

Second issue is an HDMA issue. The game enables HDMA in the beginning of the H-IRQ at H 260 on line 143. The write to $420C happens around H275-277 probably. On a real SNES the write seems to be too late for HDMA on line 143 so HDMA transfers start at line 144. `NTRL` (Line counter) of HDMA channel 0 should start with $D0. This is also what Mesen-S does. 

The developers of the game chose a very tight timing. If I patch the rom to change the H-IRQ only one pixel to 259 then the background is constantly moving 1 line up and down on a real SNES.

Here I modified the core and game so that the write happens too late for HDMA on line 143 but the core doesn't start the transfer on line 144. It just decrements the Line counter to $CF. Then it starts to write the data from $148000 on line 145 instead of 144 and $148002 on line 146 instead of 145 etc.
![hdma_144](https://user-images.githubusercontent.com/2227984/117543059-82344000-b01b-11eb-8bc6-15e5c8cdeaa6.png)

It almost looks correct but if you look very closely the last line is missing:
![20210508_145511-Full Throttle Racing_Hirq_262 (U)x2](https://user-images.githubusercontent.com/2227984/117543727-549cc600-b01e-11eb-9316-43c3cd30973d.png)

**Comment by MP2E** [comment]
Just tested and I think this is fixed in the latest changes, the bottom line appears to render correctly now

**Comment by paulb-nl** [comment]
Great work by @srg320. Works perfectly with latest changes. Even the patched game with H-IRQ 1 cycle earlier matches original hardware behavior with the background moving 1 line up and down.
