### ISSUE TITLE
Kawasaki Superbike Challenge (US) doesn't boot.

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/SNES_MiSTer#283]
The game Kawasaki Superbike Challenge (US) doesn't boot.  Nothing but a black screen.  Strangely, the European version works fine. 

Confirmed by at least 2 users.

**Comment by jeffbdavenport** [comment]
I can't seem to get any games to boot past the Nintendo logo. Am I the only one?

**Comment by AtomicShroom** [comment]
Can confirm this is fixed with the latest update! Thanks @srg320! :)
