### ISSUE TITLE
Snes Savestates

### ISSUE THREAD

**Issue by diettelo** [MiSTer-devel/SNES_MiSTer#289]
I know its not easy, but can you add Savestates?

Maybe you can talk to Robert Peip (dev of GBA and may other core or Features)
He is really good at these features.

**Comment by SegaSnatcher** [comment]
This request was already posted.  

https://github.com/MiSTer-devel/SNES_MiSTer/issues/288

**Comment by alexluecke** [comment]
Could you at least give a reason, even if unsatisfactory, for closing?

**Comment by mirkorean** [comment]
Read above. It‘s a duplicate.
