### ISSUE TITLE
Illusion of Gaia: transparency issue on diary (save) menu

### ISSUE THREAD

**Issue by michaelshmitty** [MiSTer-devel/SNES_MiSTer#29]
Illusion of Gaia on SNES classic:
![illusion of gaia snes classic](https://user-images.githubusercontent.com/114845/51829555-14eabe00-22ee-11e9-9225-d9d25cd8ca95.jpg)

Same screen on the MiSTer SNES core:
![illusion of gaia mister snes core](https://user-images.githubusercontent.com/114845/51829586-27fd8e00-22ee-11e9-8ecd-69503895d3a7.jpg)

**Comment by James-F2** [comment]
I confirm.

**Comment by sorgelig** [comment]
Confirm it wasn't photoshop? I think it's obvious.

**Comment by paulb-nl** [comment]
This was also fixed with the Fix color window commit so will be fixed next release

**Comment by michaelshmitty** [comment]
@paulb-nl confirmed fixed in the latest version. Good stuff. Thanks everyone!
