### ISSUE TITLE
Top Gear 3000 

### ISSUE THREAD

**Issue by pokevania** [MiSTer-devel/SNES_MiSTer#297]
On a fully-updated new installation, [Top Gear 3000 shows a blue background](https://imgur.com/4j3yBXJ) on "Track Description" other than the first or when a password screen precedes it. Tested to the second password point with SNES_20210713.rbf. I'm new to Mister. Let me know if I've missed important numbers. Thanks for your work.

**Comment by wwark** [comment]
Hi,
It seems this issue is already opened https://github.com/MiSTer-devel/SNES_MiSTer/issues/290
Thanks,
