### ISSUE TITLE
F-Zero Final (Hack) v0.2 Grego, CatadoorDeLatas

### ISSUE THREAD

**Issue by kousaka** [MiSTer-devel/SNES_MiSTer#299]
Core Version: SNES_20210713.rbf

This rom hack doesn't seem to run at all on the snes core. I tested the rom in an emulator and runs fine.

On Mister it just loads to black screen.

Link to romhack: https://github.com/originalgrego/FZeroFinal
It hacks all the things in the satellview sequel into the original.

**Comment by wwark** [comment]
Confirmed it works.
This ticket could be closed.

**Comment by kousaka** [comment]
My bad. I also retested this fix awhile back forgot to close. Closing now.
