### ISSUE TITLE
Graphical pixel corruption in Top Gear next to speedometer

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/SNES_MiSTer#309]
Since recently, something has broken in Top Gear: There’s a weird tiny line of corrupted pixels near the speedometer for both player 1 and 2:

[YouTube video](https://youtu.be/1XyGkEbtyyo)

**Comment by paulb-nl** [comment]
That also happens on a real SNES.

**Comment by AtomicShroom** [comment]
Well I’ll be damned! Found online footage from a real SNES console and it does indeed happen on real hardware: 

https://www.youtube.com/watch?v=K_3-3Ar8jeg
