### ISSUE TITLE
Analog output 480i isn't interlaced

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#31]
SNES analog output (VGA->RGBS) 480i isn't actually interlaced but remains 240p with shaking image (including OSD).
Seems like two consecutive filed are drawn on the exact same scan lines, instead interleaving.
Can be tested in 240p Test Suite, or A.S.P Airstrike Patrol.

480i working correctly on Genesis core.

**Comment by paulb-nl** [comment]
Fixed :D

**Comment by James-F2** [comment]
Confirm fix.
Thanks paulb-nl!
