### ISSUE TITLE
Reset settings not resetting "Video Processing" options

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/SNES_MiSTer#311]
Got black screen (with sound) in all games after latest update. It turned out to be I was using a filter that doesn't exist anymore in my SD card. Reset settings should reset that option, but it didn't do it. I had to manually set a new existing filter then image showed up.

**Comment by sorgelig** [comment]
reset settings only applicable to core's config.
Filter settings is in HPS.
I will check the issue.
