### ISSUE TITLE
Star Fox Rom hacks

### ISSUE THREAD

**Issue by terminator2k2** [MiSTer-devel/SNES_MiSTer#320]
Some Star Fox Hacks just go to black screen and have been tested and working on SD2Snes + Super NT combo, They also work fine in emulators

https://www.romhacking.net/hacks/6402/

https://www.romhacking.net/hacks/6443/

and a soon to be released Star Fox EX Hack

**Comment by kandowontu** [comment]
As the developer of said hacks, I am here if you have any questions or need an updated patch.

**Comment by terminator2k2** [comment]
@kandowontu Star Fox EX worked on mister up to :

Star_Fox_Exploration_Showcase_8.85.SFC

anything after just black screen

**Comment by birdybro** [comment]
It would be nice if a separate patch with the HUD could be made without the speed hacks. The MiSTer core has Super FX turbo and CPU Turbo which do speed up the game considerably already, so if you want to play the game with a smoother framerate for now, that might help.

**Comment by jeffkrull** [comment]
If it's any help, it seems that the problem is only with the 21 MHz FastROM hacks. The 21 MHz hack without FastROM works just fine in the SNES core.

**Comment by protogem2** [comment]
SuperFX FastROM hacks don't seem to work at all, as Stunt Race FX's FastROM hack also doesn't boot.

**Comment by kandowontu** [comment]
> SuperFX FastROM hacks don't seem to work at all, as Stunt Race FX's FastROM hack also doesn't boot.

Stunt race FX fastrom DOES boot and work. You must have a bad patch (probably from the sfc speed hacks ia page).
