### ISSUE TITLE
Bad interlaced resolution.

### ISSUE THREAD

**Issue by PepAlacant** [MiSTer-devel/SNES_MiSTer#324]
Rendering Ranger Still doesn't work, and there is a resolution issue in interlaced modes. It can be noticed in "Super Family Tennis". The selection mode is in high resolution interlaced, and it's shown incorrectly in the CRT resolutions.

**Comment by birdybro** [comment]
Yes, there is still an issue open for Rendering Ranger here --> https://github.com/MiSTer-devel/SNES_MiSTer/issues/292 - It's not closed yet.

For the interlaced resolution of Super Family Tennis... It stays on 512x224 with an occasional rare switch to 512x448i on screen transitions before the title screen. When using a RetroTink5x Pro to get the lines and frequency, it looks correct to me. 525i input lines (this is correct for NTSC), 15.75kHz input h-freq, and 59.98hz v-freq (correct for SNES).

**RetroTink 5x Pro capture from MiSTer**
![Screenshot 2022-04-10 15-03-01](https://user-images.githubusercontent.com/16388068/162639717-89238cc7-ca82-45f7-97eb-c7dd1f19383a.png)

**HDMI Capture from MiSTer**
![Screenshot 2022-04-10 15-03-22](https://user-images.githubusercontent.com/16388068/162639732-472cb7b1-c5d1-4207-bc2d-984e798e7088.png)

And in game shots are the typical 262p as usual (480i is actually 262.5p --> 525i for reference).

**Comment by PepAlacant** [comment]
I'm using a Sanyo TV with SCART. It is a PAL TV but it has support for NTSC modes. The game shows ok in the Super Famicom and in the MiST FPGA SNES core. But it shows really strange in the MiSTer core.

**Comment by PepAlacant** [comment]
I'll do the test with a PVM tomorrow and I'll try to get an image.

**Comment by PepAlacant** [comment]
![97B7061A-C9EA-4134-A486-CD43F4AADEF3](https://user-images.githubusercontent.com/75079781/162641545-f87eef3e-b55f-4720-ad17-8fe4c6c3cf20.jpeg) it's shown interlaced, but it shows as it. Wrong resolution.

**Comment by PepAlacant** [comment]
My fault ! I had a the 256px option enabled ! Sorry so much.

**Comment by birdybro** [comment]
Yup! I just was about to say that was probably what was happening. :) Glad you figured it out!

**Comment by PepAlacant** [comment]
sorry for the inconvenience !
