### ISSUE TITLE
Feature request: Add Super Gameboy games

### ISSUE THREAD

**Issue by zal16** [MiSTer-devel/SNES_MiSTer#326]
It's possible to add Sharp LR35902 (Z80 clone) simulation to archieve compatibility to Super Gameboy games?

**Comment by birdybro** [comment]
There isn't a whole lot of space left in this core. This is one of the largest cores in the entire project currently. There is already Super Game Boy functionality within the Game Boy Core (albeit lacking the SNES hardware functions that are used in a tiny handful of games).

**Comment by birdybro** [comment]
https://misterfpga.org/viewtopic.php?f=20&t=4786 - currently unofficial test build of a core that does this with MSU-1 support added as well, if you want to try it out @zal16

**Comment by wwark** [comment]
The core Super Game Boy is now released.
This ticket could be closed.
