### ISSUE TITLE
Super Mario World (U)  When you complete a stage the sound isnt right.

### ISSUE THREAD

**Issue by Retronerdy** [MiSTer-devel/SNES_MiSTer#33]

**Comment by James-F2** [comment]
Can you please be more specific?

I have recorded a real snes and mister (analog audio) and they sound absolutely identical in critical side-by-side listening test, in this game and other games.

**Comment by James-F2** [comment]
I can't reproduce this, sounds alright here.
Do you use the latest core release?

**Comment by Retronerdy** [comment]
James-F2 you are right, i tested thru HDMI and the problem is solved. Thanks

**Comment by James-F2** [comment]
Cheers.
Use the "Close" button.
