### ISSUE TITLE
Graphics glitch Secret of Mana with Scandoubler HQ2x enabled

### ISSUE THREAD

**Issue by littlegamer87** [MiSTer-devel/SNES_MiSTer#344]
See screenshot below. Pretty sure this is a regression and used to work fine, now running MiSTer v220529 with SNES v220624, USA ROM w/CRC d0176b24

Glitch appears to be related to scandoubler HQ2x. Disabling it removes it.

![somglitch](https://user-images.githubusercontent.com/17988200/177193567-40b61c3a-6816-47a7-8a61-bc07b50680ec.png)

**Comment by birdybro** [comment]
Do you have force 256px turned on in the OSD? If not, does enabling it combined with the scandoubler get rid of it?

**Comment by sorgelig** [comment]
there is some regression. I will investigate it

**Comment by littlegamer87** [comment]
> Do you have force 256px turned on in the OSD? If not, does enabling it combined with the scandoubler get rid of it?

Force 256px was disabled. Enabling it does result in the full screen being rendered, but the effect on the text is not pleasant in my opinion. See screenshot attached, letters like M, N, W all look like an H.
![somglitch](https://user-images.githubusercontent.com/17988200/177287762-9d720edb-9efd-41ac-a2a1-de553cfc80e4.png)
t on menu text is not pleasant in my opinion.

**Comment by birdybro** [comment]
Yup, it's expected for the text to get garbled, was just curious. Thanks. :)

**Comment by littlegamer87** [comment]
Confirmed as resolved in release [20220712.](https://github.com/MiSTer-devel/SNES_MiSTer/commit/198440a423264178f6ac6c630d260936ade50171)

Thank you for the amazing support!
