### ISSUE TITLE
New demo Mode7 with not good effect on MiSTer core

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/SNES_MiSTer#347]
There is the code and the SFC file at this github page
https://github.com/bbbradsmith/SNES_stuff/tree/main/dizworld

The two demos not working well are demo X and Y.

Demo X:
![20220819_153833-dizworld](https://user-images.githubusercontent.com/469461/185631294-1b12fb9e-7ef2-4b7a-ac54-855626aca08c.png)

Demo Y:
![20220819_153840-dizworld](https://user-images.githubusercontent.com/469461/185631354-bf0d9f97-cc65-4841-ab4e-b7745c108452.png)

Thanks !

**Comment by bbbradsmith** [comment]
Just to clarify, is that with the current ROM? There was an only-on-hardware glitch that I fixed a few hours after the initial release.

**Comment by wwark** [comment]
Yes I may have took the initial release with the new one it is perfect.
Thanks for your time to write those kind of demos !!!!
