### ISSUE TITLE
Hook - fastrom hack visual glitch

### ISSUE THREAD

**Issue by leonquest** [MiSTer-devel/SNES_MiSTer#357]
Played this fastrom hack on the latest version, and noticed graphical glitches on the story sequence right after the first battle with capt hook.

Wrote the hack owner and he mentions could not recreate it on snes9x.

I'm looking to recreate it on real hardware, but haven't found working cheats for level select.

**Comment by leonquest** [comment]
> Snes9x specifically has many inaccuracies when compared to original hardware. Can you test with Higan instead and report back?

I need to find usable cheat codes to test on real hardware, but haven't found one yet.

**Comment by birdybro** [comment]
So it doesn't run on Higan without cheat codes? I'm surprised it runs at all on the MiSTer core then.

**Comment by leonquest** [comment]
* I have not tested on higan and not planning to, not sure where you read that in my comments

* the cheats I mentioned are for warping into the area where the glitches were seen, I don't have time nor the will to go through the game again, even if its a short playthrough, so I'm looking for another way to fast forward to the location.

**Comment by birdybro** [comment]
Ah got it, I requested that you test it in Higan, hence my confusion toward you response.

Why are you not willing to test with Higan? snes9x is known to be inaccurate when compared to original hardware, as compared to Higan. snes9x has compatibility with specific methods of hacks that will only work on snes9x as well. The MiSTer core uses much of the documentation from no$ and from bsnes (now Higan) for it's design and is made to be very accurate to original hardware. Therefore, snes9x shouldn't really be used as a base of comparison for what the MiSTer core ought to do.

**Comment by leonquest** [comment]
Please read my first post carefully

**Comment by birdybro** [comment]
I did. You played a fastrom hack, it got graphical glitches on a later level in the game, and you mentioned the author of the hack couldn't recreate the bug in snes9x, which is an inaccurate emulator that caters to behavior that isn't present on real hardware, by design, for hacks.

**Comment by leonquest** [comment]
Tested on a 1CHIP Fat snes with an SD2Snes rev H, no glitching after the first battle with hook. I used all kinds of cheats to get there in half an hour, as unfortunately there are no GG codes out there yet for level skip or level select, and the supposed code left in the game by devs does not work.

Now, to fully confirm can someone else test again on a mister? I might find time again in the near future but maybe not today.

Word of advice if you use cheats to recreate quickly, turn them off right after finishing each stage otherwise the game will score you infinitely until it is able to drain your time, health and flying meter.

**Comment by birdybro** [comment]
Thanks for the thorough testing.

**Comment by leonquest** [comment]
Thanks to the cheats I was able to re-test relatively quick on mister.

Tested both a clean no-intro version and the fastrom hack. Could not reproduce it 🤷. I'm not sure what happened the first time, maybe it was a one-off or maybe it's part of the game's code.

Will shamefully close this one out.

**Comment by birdybro** [comment]
No shame at all! :)
