### ISSUE TITLE
Problem with some Games

### ISSUE THREAD

**Issue by fmdoppel** [MiSTer-devel/SNES_MiSTer#358]
According to the [repro from agg23](https://github.com/agg23/openfpga-SNES)  (he ported this Cors to Analogue Pocket), I’ve Problem with the following Games from Retro-Bit:
- Data East Classic Collection 
- Joe & Mac: Ultimate Caveman Collection
- Jaleco Brawlers Pack

Since I don’t own a MiSTer I can’t directly test them on this Hardware, but on Analogue Pocket they don’t work correctly. 
After booting all of them show some Logos, a Titlescreen and a Menu to Select a Game. 
In the Menu are graphical glitches. 
At least I can guess what game I select, but after hitting Start the ROM completely freeze. 

Does someone know the Problem or could check if they work on MiSTer?

Thanks!

**Comment by sorgelig** [comment]
please go to Analogue forum/github.
