### ISSUE TITLE
Feature Request - 256k SRAM option

### ISSUE THREAD

**Issue by protogem2** [MiSTer-devel/SNES_MiSTer#360]
This would allow Nested NES rom conversions (and MSU-1 arrangements) to run in the core.

Perhaps it could be implemented as an OSD menu toggle as some SNES games copy protection triggers if the SRAM is too large.

**Comment by sorgelig** [comment]
There is no resources for 256K SRAM.

**Comment by protogem2** [comment]
I understand. If you don't mind, could you please provide a more detailed explanation about why there are no resources for this?

**Comment by sorgelig** [comment]
There are not enough FPGA RAM blocks left.

**Comment by protogem2** [comment]
Thank you, that makes sense. Since this feature cannot be implemented this issue can be closed.
