### ISSUE TITLE
Allow configurable CPU/SFX overclock levels

### ISSUE THREAD

**Issue by Stealthii** [MiSTer-devel/SNES_MiSTer#363]
It would be nice to configure the level of overclock offered to the CPU and SuperFX chips, in order for custom patches like the 60fps Star Fox 2 to be considered:

https://www.romhacking.net/hacks/7170/

**Comment by sorgelig** [comment]
it's written "doesn't work on console", so most likely won't work on MiSTer too. FPGA cannot offer same level of overclock as emulators. SNES on MiSTer has no overclocking capability. It's just using some unused cycles in original HW. Otherwise it's pretty much same as real HW.
