### ISSUE TITLE
Trials of Mana:  Mode 7 graphical corruption during turtle ride

### ISSUE THREAD

**Issue by AtomicShroom** [MiSTer-devel/SNES_MiSTer#364]
A 1-frame graphical corruption can be seen during the Mode 7 turtle ride after the Volcano portion.

Video: 
https://youtu.be/ktzyXJIrlbI

Isolated screenshot:
![image0](https://user-images.githubusercontent.com/86253908/233518367-719bbd66-d295-47df-a87d-fdae64b508f6.png)

Steps to repro:
1. Load the save attached.
2. Go up into the next room and defeat the enemies (Just mash A at them)
3. Proceed into the cave.
4. Advance the dialogue/cutscene until the turtle picks you up.
Result: During the turtle ride, a 1-frame graphical corruption flashes on screen.

Note:  I was not able to reproduce this 100%, but more around 70%.

[Trials of Mana.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/11291490/Trials.of.Mana.zip)

**Comment by birdybro** [comment]
This is using the following rom, correct?

https://datomatic.no-intro.org/index.php?page=show_record&s=49&n=3797

**Comment by AtomicShroom** [comment]
The 9743dc0e one.

Oh so there's a Rev 1 out?  I wasn't even aware!

**Comment by birdybro** [comment]
you should be able to make a renamed copy of your sav file to match that other rev and give it a test

**Comment by AtomicShroom** [comment]
Strangely the saved file does not appear to be compatible with Rev 1.  It just doesn't see it and only lets me start a new game.   I guess that when they issued a patch for the rom, they also patched the save file to maintain compatibility somehow?

**Comment by birdybro** [comment]
They are both unofficial dumps from the Switch release of "Collection of Mana". They are both kinda hacky dumps from RAM after some special extraction techniques, so who knows how accurate or perfect they are in that form. It's probably all legit. Personally, I juse use the fan translation instead --> https://www.romhacking.net/translations/440/

**Comment by srg320** [comment]
@AtomicShroom, save doesn't work on both roms (CRC 173e6097 and 9743dc0e).

**Comment by AtomicShroom** [comment]
@srg320 :  Uhhh.. you're right. I'm at a complete loss for what happened. Then I have no idea which save file I ended up uploading here. And the original has long been overwritten. So I guess we're out of a save file.  Sorry for that. :/

**Comment by paulb-nl** [comment]
Here is a save that you can use. Slot 1 Seaside cavern. It comes from here: https://www.fantasyanime.com/mana/som2saves.htm

[Trials of Mana (World) (Rev 1) (Collection of Mana).sav.zip](https://github.com/user-attachments/files/17229688/Trials.of.Mana.World.Rev.1.Collection.of.Mana.sav.zip)

However this glitch can also be seen on original hardware. Here is a capture from an APU-01 console:
![trials_of_mana_glitch](https://github.com/user-attachments/assets/7965ba90-2fe9-482a-a3ec-0ba3347aa92a)

**Comment by AtomicShroom** [comment]
Oh wow. I never thought they would have left a glitch like this in the actual game. Well then let's close this if it happens on real hardware.
