### ISSUE TITLE
SNES Mario Paint: original mouse delay and stop when rubber is activated

### ISSUE THREAD

**Issue by superbonaci** [MiSTer-devel/SNES_MiSTer#365]
The issues are mentioned in this video (from 13:35 to 14:00):
https://www.youtube.com/watch?v=AyDqGdY7ffQ

- The original Nintendo mouse with mousepad has certain delay
- Clicking when moving the eraser stops the movement

The youtuber claims such things don't happen on original console.

**Comment by bikerspade** [comment]
Direct link to 13:35: https://youtu.be/AyDqGdY7ffQ&t=815
Have you tried this on original hardware?

**Comment by superbonaci** [comment]
> Direct link to 13:35: https://youtu.be/AyDqGdY7ffQ&t=815 Have you tried this on original hardware?

No I don't.

**Comment by bikerspade** [comment]
I just tried this on real hardware and a Super Nt with an OEM mouse and the behavior is identical with the eraser. This issue can be closed.

**Comment by superbonaci** [comment]
Closing then.
