### ISSUE TITLE
Super Mario World 2 - Yoshi's Island fastrom issues

### ISSUE THREAD

**Issue by kandowontu** [MiSTer-devel/SNES_MiSTer#367]
This game works on hardware with no problem. On this core, the title screen works fine but it crashes as soon as the intro starts, with invalid palettes and a halt in game execution.

Link to patch: 
https://www.patreon.com/posts/yoshis-island-1-79715848

**Comment by paulb-nl** [comment]
Which hardware did you test this on? 

GSU1/2 does not support ROM on banks $80+ so fastrom can't work with the real chip.  At least not with standard cartridge.

**Comment by kandowontu** [comment]
This was tested on an FXPak pro

**Comment by kandowontu** [comment]
This has been properly fixed with the latest unstable build. Thank you!!
