### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by bonna79** [MiSTer-devel/SNES_MiSTer#370]
You can add the save state function. Although it does not reflect the originality of the machine, I find the function very convenient for certain games.

**Comment by birdybro** [comment]
Adding savestates to this core would be very very difficult. There is also already an issue open for this and it's already closed:

https://github.com/MiSTer-devel/SNES_MiSTer/issues/289

**Comment by littlegamer87** [comment]
#288 is still open. Probably the most requested feature for this core now MSU-1 is supported, praying it will happen some day

**Comment by Toryalai1** [comment]
This ticket can be close since it is a duplicate
