### ISSUE TITLE
Merge/Update stable core please

### ISSUE THREAD

**Issue by kandowontu** [MiSTer-devel/SNES_MiSTer#372]
Can we get an update for the official build? I also think SuperFX Fastrom should be on and enable and hidden by default, as having it on causes no issues with non fastrom SuperFX games. It would eliminate confusion and issues having to turn it on after booting the rom.

**Comment by sorgelig** [comment]
ok. I will look.

**Comment by kandowontu** [comment]
Thank you SRG!!! You're the best!!
