### ISSUE TITLE
Freezes at certain stages.

### ISSUE THREAD

**Issue by Vashfairytail900** [MiSTer-devel/SNES_MiSTer#374]
Downloadable from View in Files on this page
smwx.bps in hackrom
DONUT PLAINS 4 (course #6), STAR WORLD 5 (course #136), FOREST OF ILLUSION 1 (course #11E)
The game freezes when I launch each of the following stages of the game
There are no special chips or other settings.
This is a hackromes created by patching to the original Super Mario World.
It worked fine on other emulators (BSNES, Snes9x etc) and on the actual SNES machine with SF memory cassette.

https://www.smwcentral.net/?p=profile&id=29537

**Comment by Vashfairytail900** [comment]
PS.
The game has a debug patch that allows this hackromb to travel freely to and from the Overworld.
The closest to the relevant part is the course just before the castle on the Donut Plain.

**Comment by birdybro** [comment]
I don't see a link to any patch for this hack you are referring to.

**Comment by Vashfairytail900** [comment]
Did you select View from the Files column?
The smwx.bps file in the View link is the patch for the relevant hackrom.

**Comment by MP2E** [comment]
https://bin.smwcentral.net/u/29537/smwx.bps

here's a direct link

I seem to have the same issue, I tried changing the Hardware memory settings to SD2SNES but still encountered the crash

**Comment by paulb-nl** [comment]
I have tried Donut plains 4 and it freezes in Bsnes, Ares and Mesen2.

**Comment by birdybro** [comment]
Ah I see now, sorry for the confusion. It wasn't very intuitive.

![image](https://github.com/MiSTer-devel/SNES_MiSTer/assets/16388068/ca2b93f3-e012-48e3-9c04-2be037a4a0e9)

**Comment by MP2E** [comment]
> I have tried Donut plains 4 and it freezes in Bsnes, Ares and Mesen2.

Just tested this on my 1chip SNES with an sd2snes and it also crashes just like the aforementioned emulators.

I think it’s safe to say this is a hack issue, not an issue with the core.

**Comment by Vashfairytail900** [comment]
The details of the problem are now known.
It appears that it was a RAM conflict.
The fixed version has suppressed the crashes.

**Comment by sorgelig** [comment]
So it's fixed and can be closed?

**Comment by paulb-nl** [comment]
Can be closed. It is not an issue of this core.
