### ISSUE TITLE
Super Mario Bros Maker by Infidelity not working (256KB sram needed)

### ISSUE THREAD

**Issue by kandowontu** [MiSTer-devel/SNES_MiSTer#378]
Is there any way to support 256KB sram? it works on hardware and analogue NT, as well as the original bsnes 115 and mesen.

Thank you!

https://t.co/20Rpr22dFi

**Comment by littlegamer87** [comment]
https://github.com/MiSTer-devel/SNES_MiSTer/issues/296

Same topic. Please close issue.

**Comment by kandowontu** [comment]
> #296
> 
> Same topic. Please close issue.

Will do.
