### ISSUE TITLE
CPU: Turbo setting not working on latest build (09252024)

### ISSUE THREAD

**Issue by italiangrandma** [MiSTer-devel/SNES_MiSTer#382]
Setting the CPU Setting to Turbo causes any game I load to immediately crash to a black screen or garbled graphics. 

Potentially related to #381 ?

**Comment by ZZZyeahZZZ** [comment]
@italiangrandma  Thanks for reporting this. Tested first with Gradius 3, then with more games:

Same for me, CPU set to "turbo" in the SNES core crashes in SNES_20240919.rbf.

"Turbo" in SNES_20240408.rbf is functional.

**Comment by sorgelig** [comment]
@srg320 
i believe it's related to a new SDRAM controller.

**Comment by wwark** [comment]
It seems fixed no more issue on my side !

**Comment by italiangrandma** [comment]
yep, appears to be fixed with ltest unstable build (10012024)!

**Comment by ZZZyeahZZZ** [comment]
I've tested https://github.com/MiSTer-unstable-nightlies/SNES_MiSTer/releases/download/unstable-builds/SNES_unstable_20241001_16fe7f.rbf , and it appears the "turbo" CPU setting is functional (at least with gradius 3).
