### ISSUE TITLE
EMUDetect - issue

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/SNES_MiSTer#383]
With the last commit of 01/10/2024, after loading the core we have not correct screen.
If we reset on the OSD, the correct screen is shown.

Thanks,

**Comment by MP2E** [comment]
I see this issue too, it happens no matter what the WRAM option is set to in the Hardware menu

**Comment by MP2E** [comment]
This is now fixed in the newest changes!

**Comment by wwark** [comment]
thank for the test and the quick fix :+1:
