### ISSUE TITLE
BSX Loading gets stuck just after the welcome screen

### ISSUE THREAD

**Issue by terminator2k2** [MiSTer-devel/SNES_MiSTer#385]
Using the unstable snes build im getting stuck just after the welcome screen. 

https://github.com/MiSTer-unstable-nightlies/SNES_MiSTer/releases/download/unstable-builds/SNES_unstable_20241007_11ef03.rbf

**Comment by Zet-sensei** [comment]
The autobuild compilation was borked.

Manual compilation fixed the issue.
