### ISSUE TITLE
Please add an overscan on/off option

### ISSUE THREAD

**Issue by kandowontu** [MiSTer-devel/SNES_MiSTer#386]
SNES has overscan features that would be amazing to be able to toggle on and off for certain games.

Hopefully adding this feature will be a trivial task!

**Comment by birdybro** [comment]
Which games specifically would benefit from this?

**Comment by kandowontu** [comment]
> Which games specifically would benefit from this?

You can find a list here:
https://snes.nesdev.org/wiki/Uncommon_graphics_mode_games#Overscan_(239_lines)

This is also for future ports and romhack projects to be able to make use of this area.

**Comment by birdybro** [comment]
Do you have examples where the MiSTer core is missing something versus bsnes for example? I tested Super Tetris 3:

bsnes:
![image](https://github.com/user-attachments/assets/22cea4a4-8557-4d42-b80c-9da23a7a713d)

MiSTer core:
![image](https://github.com/user-attachments/assets/59c548a5-eece-4420-8d59-e15da7061873)

I don't think I see any difference between to two (despite my filters being different and MiSTer defaulting to DAR more accurately).

**Comment by kandowontu** [comment]
After reviewing it, it appears that MiSTer ALWAYS displays the overscan area.

This has been troublesome for some NES->SNES port developers who have relied on the overscan area to place graphics for use in some cases.

It may also be useful for getting better full picture by removing the overscan on non-overscan games.

**Comment by paulb-nl** [comment]
Toggling overscan is done by software so I don't understand what you mean by "troublesome".

"Getting better full picture" is not possible because that means Vblank time is shorter and games will show glitched graphics.

**Comment by kandowontu** [comment]
Understandable. I'll close the issue and port developers will just have to make sure to disable the overscan register for MiSTer compatibility.
