### ISSUE TITLE
Super Mario RPG - Crash on 1st Level Up screen

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/SNES_MiSTer#39]
New with the SA1 chip addition the game is playable.  This bug will take about 10 minutes after starting a new game to replicate or use the attached sav.  Go kill one group of monsters and you'll level up.  At the first level up bonus screen, the game hard locks, with background music continuing.

[Super Mario RPG - save.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/2898699/Super.Mario.RPG.-.save.zip)

**Comment by molnara** [comment]
I can confirm this is an issue.

**Comment by Hewhoisred** [comment]
Further info:  Level up screen uses character conversion dma.
This was apparently a very difficult bug to squash on the SD2SNES FPGA, according to Redguy, one of it's developers.

**Comment by Hewhoisred** [comment]
Fixed with the last update.  You can close.  Thanks very, very much!
