### ISSUE TITLE
Star Ocean (96MBit uncompressed) will not boot

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#43]
The uncompressed game will boot to black screen.
It is 12.5MByte, and maybe exceeds the MiSTer rom capacity.

The regular SDD-1 (compressed) version works fine.

**Comment by sorgelig** [comment]
This is not a bug. It's just hack using some specific mapper.
Marked as enhancement with low priority and the main priority is to fix the bugs in original games.

**Comment by James-F2** [comment]
It boots now, thank you!
