### ISSUE TITLE
Kirby Super Star intro slowdown

### ISSUE THREAD

**Issue by paulb-nl** [MiSTer-devel/SNES_MiSTer#47]
In the intro when Kirby is flying over the grass there is slowdown in some parts. Video: https://www.youtube.com/watch?v=Mc5dhkkBWdw

During the slowdown a blue bar flickers in the background just above the grass.
![kirby_glitch](https://i.imgur.com/TawOwcNl.png)

On real hardware there is no slowdown: https://youtu.be/tGt0QQkkY1c?t=112

It seems that the early SA-1 core on SD2SNES had the same problem: https://youtu.be/Jw5_Z3CE2SM?t=958

**Comment by James-F2** [comment]
Using this SA-1 Speed Test rom:
https://github.com/VitorVilela7/SnesSpeedTest

The clock speeds look exactly like on the real hardware SA-1, but the game still stutters.

**Comment by paulb-nl** [comment]
Awesome work by srg320. Works fine now

**Comment by sorgelig** [comment]
TG3000 is fixed as well!

**Comment by sorgelig** [comment]
I close it as fixed.
