### ISSUE TITLE
F1 ROC II, freezes

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#50]
The game freezes in various locations.
It froze in the menu and during gameplay for me.

I am aware that this report in on the forum, and I think all issues should be reported on github for organization.

**Comment by James-F2** [comment]
BTW, the game has saves, but there is no Save/Load in OSD.

**Comment by sorgelig** [comment]
Currently it's impossible to save/load saves in this game cause save memory is in inaccessible memory.
May be in the future it will be changed.

**Comment by sorgelig** [comment]
The original freeze issue is fixed, so i close this issue.
