### ISSUE TITLE
Small graphical glitches during door transitions in Super Metroid

### ISSUE THREAD

**Issue by Eyedunno** [MiSTer-devel/SNES_MiSTer#55]
Some short lines of white pixels appear for a frame at a time on most door transitions.

To replicate it, just go from room to room a few times and pay close attention when the screen is mostly black and transitioning.

Here is a save, but it's not really necessary, since this happens in most doors, so any save should do fine.
[Super Metroid (JU) [!].zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/2965102/Super.Metroid.JU.zip)

And here is a picture of the issue:
![smetbug2](https://user-images.githubusercontent.com/45522237/54338308-bacc6080-45ee-11e9-9f06-ac713eac968c.png)

Finally, here's a video:
https://youtu.be/E0xnwtNxumQ
It happens in RGB or HDMI on MiSTer, but does not happen on real hardware or Super Nt.

**Comment by James-F2** [comment]
Fixed with srg320 April 2019 commits.
