### ISSUE TITLE
Mister FPGA - Marvelous - Mouhitotsu no takarajima 1.07

### ISSUE THREAD

**Issue by terminator2k2** [MiSTer-devel/SNES_MiSTer#59]
bug in marvelous , chapter 5  maps

![image0](https://user-images.githubusercontent.com/48845336/54858223-75e5af80-4cfb-11e9-8c0b-93f68a3c2094.jpg)

should look like 

![image0 (1)](https://user-images.githubusercontent.com/48845336/54858249-96ae0500-4cfb-11e9-91ec-a197d59ca4d8.jpg)

save file 

[Marvelous_-_1.07.sav.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/2998767/Marvelous_-_1.07.sav.zip)

using the save file follow this youtube to 1min 30 seconds

 https://www.youtube.com/watch?v=Q8rc7B0vu4U&t=96s

**Comment by srg320** [comment]
What hardware was the second photo taken from?
Interesting, on this rom bug appears both on bsnes, snes9x and no&sns, but in Japanese and English by Tashi versions bug does not appear anywhere.

**Comment by terminator2k2** [comment]
yes just noticed that this issue only appears on 1.07 version of the translation, just tried the other versions and they are fine, so ill close this...
