### ISSUE TITLE
Star Ocean flickering map

### ISSUE THREAD

**Issue by softtest1** [MiSTer-devel/SNES_MiSTer#71]
Go out into the field. A map will be visible on the side of the screen but it will have flickering lines when you move around.

Save file: https://ufile.io/6whq0jne

I'm playing with an unmodified Japan rom.

**Comment by James-F2** [comment]
Seems to be fixed with the latest PPU fix here (2019 May 6th):
https://github.com/MiSTer-devel/SNES_MiSTer/commit/d280b5affc7e416787bf6af23844aac38ef829d8

Please confirm when the core is updated.

**Comment by softtest1** [comment]
Seems fixed. Thank you.
