### ISSUE TITLE
DSP-2 Dungeon Master

### ISSUE THREAD

**Issue by Hewhoisred** [MiSTer-devel/SNES_MiSTer#83]
This game doesn't work properly.  It is the only game that uses the DSP-2 special chip.

It only takes a moment to see the problem.  Shortly after you start the game, entering through the door, you'll quickly see heavy corruption to the graphics, and if you move forward, the game will soon lock up.

attached are some screenshots:
![20190519_222604-Dungeon Master (USA)](https://user-images.githubusercontent.com/47957258/57998331-dab45080-7a85-11e9-9ea3-d3ae9c327cf2.png)
![20190519_222620-Dungeon Master (USA)](https://user-images.githubusercontent.com/47957258/57998332-dab45080-7a85-11e9-8d62-359e02728b04.png)
![20190519_222637-Dungeon Master (USA)](https://user-images.githubusercontent.com/47957258/57998333-dab45080-7a85-11e9-8821-642bb8addbec.png)

Tested with the USA, EUR and JAP roms.

**Comment by James-F2** [comment]
Fixed in 20190609.

**Comment by Hewhoisred** [comment]
Confirmed fixed.
