### ISSUE TITLE
Yoshi's Island, see-through tunnels are reversed.

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/SNES_MiSTer#84]
With release 2019.05.17.
See-through tunnels are now reversed in stage 1-2,, and there is no transition animation of the tunnels.
When you enter a tunnel it should become transparent with transition animation ,, when you exit it should transition to solid.

See here as it should be:
https://youtu.be/U8btNneN8ew?t=13m45s

Probably related to this fix:
https://github.com/MiSTer-devel/SNES_MiSTer/issues/72

**Comment by James-F2** [comment]
Fixed.

**Comment by birdybro** [comment]
@James-F2 can you just confirm that the latest commit didn't cause a regression with this issue and the other one you linked, for me? LMULT instruction was fixed and just want to be sure. Thank you!
