### ISSUE TITLE
Final Fantasy 2/4 Visual Glitch During Screen Transitions

### ISSUE THREAD

**Issue by MordecaiWalfish** [MiSTer-devel/SNES_MiSTer#86]
There is a small line of messed up pixels near the bottom of the screen throughout the game during screen transitions. You can test this easily by starting a game and going through the intro (~5minutes) and when you are able to control the character, simply walk down through the door below you, and then back up to the room you started in. (example pics attached)
![2019-05-26 17-43-00](https://user-images.githubusercontent.com/40709481/58388214-970b9a80-7fe1-11e9-84d3-c2b652b1e2e7.png)
![2019-05-26 17-43-00_00 33](https://user-images.githubusercontent.com/40709481/58388219-a0950280-7fe1-11e9-9f9b-9b501f455e75.png)

I had also noticed that you can see this glitch when exiting battles when the screen transitions back to the normal overhead view.

The following video shows the glitch happening when walking between rooms in the final dungeon, and after a fight: https://youtu.be/4waKEgIZS2o

James-F has confirmed with me that this does not occur on original SNES hardware.

**Comment by MordecaiWalfish** [comment]
The glitch happens specifically in the frame between when the screen transition effect ends and your character appears. 
This is the reason the main character is not visible in the screenshots shown, as the glitch goes away the instant the player character appears.

**Comment by James-F2** [comment]
I see the same thing on a real 3chip snes.

![5 yellow pixels](https://user-images.githubusercontent.com/31185814/58499764-78e09e80-8189-11e9-9943-fb6ae7c7a626.jpg)

7 seconds video:
[3chip snes ff2 transition.zip](https://github.com/MiSTer-devel/SNES_MiSTer/files/3228976/3chip.snes.ff2.transition.zip)

**Comment by MordecaiWalfish** [comment]
closing this as it seems to be showing up on real snes hardware now that tested with a "3 chip" model
