### ISSUE TITLE
Errors in new translation for Thracia﻿ ﻿776

### ISSUE THREAD

**Issue by mabrilG** [MiSTer-devel/SNES_MiSTer#94]
Have been released a new fan translation for Fire Emblem: Thracia 776. The game begins but have corrupted graphics and fonts errors.
This patch game only work in some emulators like is described in the web page of the autors because﻿ the﻿﻿﻿ ROM ﻿has been expanded.
 
Maybe can support this type of roms.

https://forums.serenesforest.net/index.php?/topic/85081-fe5-project-exile-thracia-776-script-and-menu-translation-fully-complete-and-released/

Thanks.

**Comment by James-F2** [comment]
> This patch game only work in some emulators

Does it work on real console and sd2snes?
If not, maybe you should improve the patch to work on real console first?

**Comment by paulb-nl** [comment]
SD2SNES fix: https://krikzz.com/forum/index.php?topic=7230.0

**Comment by James-F2** [comment]
optiroc on discord said it's **reversed ExLoROM**,, no other game does something similar to this.
@sorgelig can update Main_MiSTer to support this kind of rom, or the developer could just convert it to standard ExLoROM for it to work.

**Comment by sorgelig** [comment]
why need change the core for a single weird ROM instead to ask the translator make it standard?

**Comment by Kitrinx** [comment]
Normally I would agree that adding a one-off exception for a single hack would just be clutter. 

So, after discussing this, it seems the only way make a LoROM game larger than 4mb is to either add a special chip to it, which is difficult and makes repros hard, or to invent a new mapper "ExLoROM". This game being LoROM the authors chose to make it ExLoROM. SNES9X recently added support for this mapping with this kind of scenario in mind, and I think it is likely that we see more of these pop up in the future, now that it is becoming supported by other things.

It's a high profile game and we have support for things like the Star Ocean hack, so maybe it's not that unreasonable to add for now and for the future.

**Comment by Optiroc** [comment]
It was my lack of sleep talking when I said “reversed ExLoROM” – this is indeed (the one example of?) ExLoROM. 

I concur with Kitrinx; it is a sound (and simple) extension to regular mode 0x20 that won’t break any existing games, and seems as such a very reasonable addition to SNES_MiSTer.

**Comment by sorgelig** [comment]
ok

**Comment by Kitrinx** [comment]
Works corrects now, thank you.
![thracia](https://user-images.githubusercontent.com/15653832/59313600-4cdc1780-8c77-11e9-959a-61f7fbae9770.PNG)

**Comment by mabrilG** [comment]
Thank you Sorgelig, now we can play this great game in our dear Mister.
